# Generated by Django 3.1.1 on 2020-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField()),
                ('ident', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('a_name', models.CharField(max_length=100)),
                ('a_lat', models.FloatField()),
                ('a_lon', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('continent', models.CharField(max_length=3)),
                ('iso_country', models.CharField(max_length=50)),
                ('iso_region', models.CharField(max_length=50)),
                ('municipal', models.CharField(max_length=50)),
                ('scheduled_service', models.CharField(max_length=50)),
                ('gps_code', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=50)),
                ('local_code', models.CharField(max_length=50)),
                ('home_link', models.CharField(max_length=200)),
                ('wikipedia_link', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
